fl.outputPanel.clear();

var timeline  = fl.getDocumentDOM().getTimeline();
for (var i = 0; i < timeline.layers.length; i++)
{
    var layer = timeline.layers[i];
    fl.trace(layer.name);
    // if (stage[i].instanceType =="bitmap")
    // {
    //     addBitmap(stage[i],'');
    // }
    // else if (stage[i].instanceType == "symbol")
    // {
    //     addGroup (stage [i]);
    // }
}
// create = create.concat(")");
// var output = "// Generated by Flash to Phaser v1.0 at " + new Date().toUTCString () + "\n\n";
// output = output.concat("\n");
// output = output.concat('function preload() {');
// output = output.concat("\n\n");

// for (var i = 0; i < preload. length; i++){
//     var name = preload[i].substr(0, preload[i]. length - 4);
//     output = output. concat(" game. load. image('" + name + "', '" + preload[i] + "');\n");
// }
// output = output.concat("\n");
// output = output.concat('}');
// output = output.concat("\n\n");
// output = output.concat(create);
// fl.trace("Generating ...");


// var f = fl.browseForFileURL("save","Select a JS", "Phaser JS Document (*.js)", "json");
// fl.outputPanel.clear();
// fl.trace(output);
// fl.outputPanel.save(f);
// fl.trace("Saved to " + f);

